services:
  redis:
    image: redis/redis-stack
    container_name: redis
    # In production, keep Redis internal unless you need external access
    # ports:
    #   - "6379:6379"
    #   - "8001:8001"

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    env_file:
      - ./ecommerce-backend/.env
    volumes:
      - mongo_data:/data/db
    # In production, keep Mongo internal unless you need external access
    # ports:
    #   - "27017:27017"

  server:
    build:
      context: ./ecommerce-backend
      dockerfile: Dockerfile   # points to your existing Dockerfile
    container_name: server
    ports:
      - "4000:4000"
    env_file:
      - ./ecommerce-backend/.env
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
      # MONGO_URI is read from backend .env
    depends_on:
      - redis
      - mongo

  client:
    build:
      context: ./ecommerce-frontend
      dockerfile: Dockerfile   # points to your existing Dockerfile
    container_name: client
    ports:
      - "80:80"
    env_file:
      - ./ecommerce-frontend/.env
    depends_on:
      - server

volumes:
  mongo_data:
